// 갤러리 목록. 새 항목은 맨 위에 한 줄 추가하고 thumbs/NN.jpg(GPT), thumbs/g/NN.jpg(Gemini) 썸네일을 넣는다.
window.GALLERY = [
  {"n": 88, "name": "1950년패션화보", "desc": "1950년대 파리 오뜨 쿠튀르 흑백 패션 매거진 광고 화보", "dir": "1950년패션화보", "doc": "1950s_Vintage_Couture_Fashion_Editorial_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 87, "name": "라이프매거진", "desc": "1950~70년대 미국 LIFE 매거진 빈티지 포토저널리즘 표지", "dir": "라이프매거진", "doc": "Vintage_LIFE_Magazine_Cover_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 86, "name": "일본포스터", "desc": "1970~80년대 일본 쇼와 실크스크린 영화 포스터 초상화", "dir": "일본포스터", "doc": "Showa_Retro_Silkscreen_Movie_Poster_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 85, "name": "가을여인", "desc": "늦가을 해바라기와 골든아워 감성 페인팅 초상화", "dir": "가을여인", "doc": "Autumn_Woman_Sunflower_Portrait_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 84, "name": "미친모자장수", "desc": "이상한 나라의 앨리스 매드 해터 하이엔드 패션 포스터", "dir": "미친모자장수", "doc": "Mad_Hatter_Editorial_Poster_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 83, "name": "일본야구귀요미", "desc": "NPB 일본 프로야구 구단별 미니미 3D 아트토이 캐릭터 포스터", "dir": "일본야구귀요미", "doc": "Japanese_Baseball_Cutie_3D_Art_Toy_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 82, "name": "한국야구귀요미", "desc": "KBO 구단별 미니미 3D 아트토이 야구 캐릭터 포스터", "dir": "한국야구귀요미", "doc": "Korean_Baseball_Cutie_3D_Art_Toy_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 81, "name": "미니미 아트토이 콘셉트 워크", "desc": "3등신 디자이너 피규어 미니미 아트토이 콘셉트 워크", "dir": "미니미 아트토이 콘셉트 워크", "doc": "Minimi_Art_Toy_Concept_Work_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 80, "name": "조선의 여검사", "desc": "오뜨 쿠튀르 흑적 금박 검무복 조선 여검사 화보", "dir": "조선의 여검사", "doc": "Joseon_Female_Swordsman_Couture_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 79, "name": "뾰루퉁인형", "desc": "명화 코스튬 뾰루퉁 미니미 아트토이 증명사진", "dir": "뾰루퉁인형", "doc": "Pouty_Art_Toy_Masterpiece_ID_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 78, "name": "내 애니케릭터", "desc": "80~2000년대 국내 방영 애니 주인공 매칭 코스프레", "dir": "내 애니케릭터", "doc": "Classic_Anime_Hero_Cosplay_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.png"},
  {"n": 77, "name": "거대 수호수", "desc": "관상 매칭 거대 수호수 × 수인 소녀 판타지 컨셉 아트", "dir": "거대 수호수", "doc": "Guardian_Beast_Beastkin_Girl_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 76, "name": "순정만화", "desc": "1980~90년대 정통 순정만화 단행본 표지 일러스트", "dir": "순정만화", "doc": "Retro_Shoujo_Manga_Cover_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 75, "name": "판타지 패션화보", "desc": "도플갱어 듀얼 페르소나 판타지 패션 매거진 표지", "dir": "판타지 패션화보", "doc": "Doppelganger_Fantasy_Magazine_Cover_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 74, "name": "여왕과수호동물", "desc": "관상 기반 여왕과 수호동물 판타지 에디토리얼", "dir": "여왕과수호동물", "doc": "Queen_and_Guardian_Animal_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 73, "name": "이불 김밥 미니미", "desc": "3D 스타일라이즈드 이불 김밥 미니미 캐리커처", "dir": "이불 김밥 미니미", "doc": "Blanket_Roll_Minimi_Art_Toy_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 72, "name": "플라워 파라솔 런웨이", "desc": "오트 쿠튀르 플라워 파라솔 런웨이 에디토리얼", "dir": "플라워 파라솔 런웨이", "doc": "Flower_Parasol_Runway_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 71, "name": "자수초상화", "desc": "조선 전통 규방자수 & 궁중자수 초상화", "dir": "자수초상화", "doc": "Korean_Embroidery_Portrait_Prompt.md", "gemini": "제미나이(규방자수).jpg", "gpt": "GPT(규방자수).jpg"},
  {"n": 70, "name": "패션잡지", "desc": "90년대 레트로 스트리트 패션 잡지 한국어판", "dir": "패션잡지", "doc": "Retro_90s_Street_Fashion_Magazine_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 69, "name": "할로윈코스튬", "desc": "관상 기반 할로윈 코스튬 시네마틱 화보", "dir": "할로윈코스튬", "doc": "Physiognomy_Halloween_Costume_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 68, "name": "아이돌", "desc": "K-pop 걸그룹 음악방송 무대 직캠 화보", "dir": "아이돌", "doc": "Kpop_Idol_Stage_Fancam_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 67, "name": "전투메이드", "desc": "로맨스 판타지 전투 메이드 라이플 표지 일러스트", "dir": "전투메이드", "doc": "Combat_Maid_Rifle_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 66, "name": "치파오", "desc": "시누아즈리 빅토리안 맥시멀리즘 치파오 화보", "dir": "치파오", "doc": "Chinoiserie_Cheongsam_Editorial_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 65, "name": "구미호", "desc": "신비로운 달빛 구미호 실사 판타지 시네마틱 화보", "dir": "구미호", "doc": "Nine_Tailed_Fox_Gumiho_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 64, "name": "나른한숏컷", "desc": "나른한 픽시 숏컷 세미리얼리스틱 일러스트", "dir": "나른한숏컷", "doc": "Languid_Pixie_Cut_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 63, "name": "프라모델", "desc": "건프라 스타일 런너 미조립 피규어 키트", "dir": "프라모델", "doc": "Plastic_Model_Runner_Kit_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 62, "name": "화이트 카나리아", "desc": "하이엔드 3D 아트토이 캐릭터 '화이트 카나리아' 일러스트", "dir": "화이트 카나리아", "doc": "White_Canary_Art_Toy_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 61, "name": "마리오네트", "desc": "18세기 소극장 무대 꼭두각시 '마리오네트' 필름 실사", "dir": "마리오네트", "doc": "Marionette_Theater_Stage_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 60, "name": "블루로즈 화이트", "desc": "하이엔드 로열 블루 룩 & 블루 로즈 화이트 스튜디오 화보", "dir": "블루 로즈 화이트 스튜디오", "doc": "Royal_Blue_Look_Fashion_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 59, "name": "코스모스", "desc": "60년대 모드 스타일 황화코스모스 런웨이 패션 화보", "dir": "코스모스 런웨이", "doc": "Cosmos_Runway_Mod_Fashion_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 58, "name": "비오는날 창밖에서", "desc": "비 오는 저녁 통유리창 너머 감성 시네마틱 화보", "dir": "비오늘날의창밖에서", "doc": "Rainy_Day_Window_Melancholy_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 57, "name": "별빛 피아노", "desc": "코스믹 판타지 크리스털 '별빛 피아노' 세미리얼 일러스트", "dir": "별빛 피아노", "doc": "Starlight_Crystal_Piano_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 56, "name": "다게레오타입", "desc": "1850년대 다게레오타입 은판 사진 초상화", "dir": "다게레오타임사진", "doc": "Daguerreotype_Portrait_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 55, "name": "어진", "desc": "조선 왕실 어진 양식 전통 비단 채색 초상화", "dir": "어진", "doc": "Royal_Portrait_Eojin_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 54, "name": "8090필름", "desc": "1980-90년대 빈티지 35mm 로우파이 필름 스냅", "dir": "8090필름", "doc": "Retro_90s_Film_Snap_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 53, "name": "포슬린돌", "desc": "몽환적인 파스텔 톤 포슬린 돌 3D 일러스트", "dir": "포슬린돌", "doc": "Porcelain_Doll_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 52, "name": "어부바", "desc": "청량한 여름 호숫가 '어부바' 로맨스 화보", "dir": "어부바", "doc": "Piggyback_Summer_Romance_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 51, "name": "뷰티포트레이트", "desc": "세미리얼리스틱 에디토리얼 '뷰티 포트레이트'", "dir": "뷰티포트레이트", "doc": "Semi_Realistic_Beauty_Portrait_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 50, "name": "빨간망토", "desc": "다크 판타지 고딕 호러 '빨간 망토'", "dir": "빨간망토", "doc": "Little_Red_Riding_Hood_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 49, "name": "검은 고양이", "desc": "심리적 고딕 호러 '검은 고양이' 포트레이트", "dir": "검은 고양이", "doc": "Black_Cat_Gothic_Horror_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 48, "name": "벨벳마녀", "desc": "하이퍼리얼 고딕 판타지 '벨벳 마녀'", "dir": "벨벳마녀", "doc": "Velvet_Witch_Gothic_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 47, "name": "검은베일", "desc": "고딕 판타지 패션 에디토리얼 '검은 베일'", "dir": "검은베일", "doc": "Black_Veil_Gothic_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 46, "name": "오팔아이프리즘선그라스", "desc": "오팔 아이 & 프리즘 선글라스 뷰티 에디토리얼", "dir": "오팔아이프리즘선그라스", "doc": "Opal_Eyes_Prism_Sunglasses_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 45, "name": "2중인격앨리스", "desc": "2중인격 앨리스 실사 화보", "dir": "2중인격앨리스", "doc": "Dual_Persona_Alice_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 44, "name": "로맨스판타지 초상화", "desc": "완전 정면 로맨스 판타지 디지털 페인팅 초상화", "dir": "로맨스판타지 초상화", "doc": "Romance_Fantasy_Frontal_Portrait_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 43, "name": "홀로그램 로즈", "desc": "고딕 로맨틱 '홀로그램 로즈' 반실사 일러스트", "dir": "홀로그램 로즈", "doc": "Hologram_Rose_Gothic_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 42, "name": "달빛 아래의 동양 여인", "desc": "미드저니풍 반실사 디지털 일러스트", "dir": "달빛 아래의 동양 여인", "doc": "Moonlight_Oriental_Woman_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 41, "name": "사진을팝아트로", "desc": "디지털 페인팅 & 팝아트 일러스트 변환", "dir": "사진을팝아트로", "doc": "Pop_Art_Digital_Painting_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 40, "name": "햇살좋은어느날", "desc": "청춘 로맨스 영화 스틸컷 '햇살 좋은 어느 날'", "dir": "햇살좋은어느날", "doc": "Sunny_Day_Romance_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 39, "name": "이니셜포니", "desc": "이니셜 포니 야간 다운힐 레이싱 & 운전자 극클로즈업", "dir": "이니셜포니", "doc": "Initial_Pony_Racing_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 38, "name": "반려동물 수묵화", "desc": "조선시대 화원풍 반려동물 전통 민화·채색 수묵화", "dir": "반려동물 수묵화", "doc": "Pet_Korean_Ink_Painting_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 37, "name": "벽쿵 고백", "desc": "로맨스 드라마 '벽쿵 고백' 스틸컷", "dir": "벽쿵 고백", "doc": "Wall_Slam_Confession_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 36, "name": "베르사유장미", "desc": "오스칼 스타일 근위대장 시네마틱 화보", "dir": "베르사유장미", "doc": "Rose_of_Versailles_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 35, "name": "플라맹고", "desc": "플라멩코 댄서 & 장화 신은 고양이", "dir": "플라맹고", "doc": "Flamenco_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 34, "name": "진 소재로 만든 한복", "desc": "모던 리디자인 진 한복 로판 화보", "dir": "진 소재로 만든 한복", "doc": "Denim_Hanbok_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 33, "name": "검무", "desc": "조선 궁궐 기녀 검무(劍舞) 시네마틱", "dir": "검무", "doc": "Joseon_Gisaeng_Sword_Dance_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 32, "name": "여우코스프레", "desc": "로판풍 여우·고양이 코스프레 판타지 패션 화보", "dir": "여우코스프레", "doc": "Fox_Cosplay_Fantasy_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 31, "name": "옥토끼", "desc": "SF 달 기지 옥토끼 메카 배틀슈트", "dir": "옥토끼", "doc": "Moon_Rabbit_Mecha_Suit_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.webp"},
  {"n": 30, "name": "엔딩요정", "desc": "K-pop 아이돌 음악방송 '엔딩 요정'", "dir": "엔딩요정", "doc": "Ending_Fairy_Idol_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 29, "name": "몽환수채화", "desc": "몽환적 수채화 인물화 (마스터 템플릿)", "dir": "몽환수채화", "doc": "Dreamy_Watercolor_Portrait_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.png"},
  {"n": 28, "name": "아크릴유화", "desc": "사진을 캔버스 아크릴 인물화로 변환", "dir": "아크릴유화", "doc": "Acrylic_Portrait_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.png"},
  {"n": 27, "name": "지옥의신부", "desc": "지옥의 신부 다크 판타지 시네마틱", "dir": "지옥의신부", "doc": "Bride_of_Hell_Dark_Fantasy_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 26, "name": "성녀와 악마", "desc": "거울 속 성녀와 악마 로판 일러스트", "dir": "성녀와 악마", "doc": "Saint_and_Devil_Mirror_Fantasy_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 25, "name": "햅번 스타일", "desc": "클래식 오드리 헵번풍 패션 뷰티 일러스트", "dir": "햅번 스타일", "doc": "Hepburn_Style_Fashion_Portrait_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 24, "name": "가든 웨딩사진", "desc": "로맨틱 유럽풍 가든 웨딩 포트레이트", "dir": "가든 웨딩사진", "doc": "Romantic_Garden_Bridal_Portrait_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 23, "name": "흑백웨딩사진", "desc": "시네마틱 흑백 파인아트 웨딩 포트레이트", "dir": "흑백웨딩사진", "doc": "Cinematic_BW_Bridal_Portrait_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 22, "name": "요술공주 밍키 한복", "desc": "로판풍 요술공주 밍키 마법소녀 한복", "dir": "요술공주 밍키 한복", "doc": "Magical_Princess_Minky_Hanbok_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 21, "name": "개화기", "desc": "1930년대 경성 모던걸 흑백 은염 사진", "dir": "개화기", "doc": "Gyeongseong_Modern_Girl_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 20, "name": "중경삼림", "desc": "1994년 홍콩 영화 필름 스틸컷", "dir": "중경삼림", "doc": "Chungking_Express_Film_Still_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.png"},
  {"n": 19, "name": "펜선 이미지", "desc": "볼펜 드로잉 & 형광펜 청춘 스케치", "dir": "펜선 이미지", "doc": "Ballpoint_Highlighter_Portrait_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 18, "name": "세일러문 한복버전", "desc": "로판풍 세일러문 정통 한복", "dir": "세일러문 한복버전", "doc": "Sailor_Moon_Hanbok_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 17, "name": "못난이 인형", "desc": "70~80년대 빈티지 소프비 인형", "dir": "못난이 인형", "doc": "Vintage_Motnani_Doll_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.png"},
  {"n": 16, "name": "구체관절인형", "desc": "1:3 스케일 레진 BJD 인형", "dir": "구체관절인형", "doc": "Ball_Jointed_Doll_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.png"},
  {"n": 15, "name": "바리데기", "desc": "무조신 다크 판타지 시네마틱", "dir": "바리데기", "doc": "Baridegi_Dark_Fantasy_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 14, "name": "심청전", "desc": "연꽃 환생 실사 판타지", "dir": "심청전", "doc": "Shimcheong_Lotus_Fantasy_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 13, "name": "RPG 캐릭터", "desc": "동양 판타지 수채화 컨셉아트", "dir": "RPG 캐릭터", "doc": "Goguryeo_Fantasy_RPG_Character_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 12, "name": "사진을수채화로", "desc": "투명한 습식 수채화 인물화", "dir": "사진을수채화로", "doc": "Watercolor_Portrait_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.png"},
  {"n": 11, "name": "사신수와무사", "desc": "사신수와 조선 철릭 무사", "dir": "사신수와무사", "doc": "Four_Gods_Warrior_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.png"},
  {"n": 10, "name": "로판표지생성", "desc": "웹소설 로맨스판타지 표지 일러스트", "dir": "로판표지생성", "doc": "Romance_Fantasy_Cover_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 9, "name": "물아일체", "desc": "풍경 동화(Landscape Dissolve)", "dir": "물아일체", "doc": "Landscape_Dissolve_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 8, "name": "귀여운 프라모델", "desc": "SD 치비 1/12 스케일 조립형 피규어", "dir": "귀여운 프라모델", "doc": "Cute_Plastic_Model_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 7, "name": "중세 판타지", "desc": "에픽 판타지 (그라디언트 디졸브)", "dir": "중세 판타지", "doc": "Medieval_Fantasy_Portrait_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 6, "name": "벽화", "desc": "거리 스텐실 그래피티 벽화", "dir": "벽화", "doc": "Stencil_Graffiti_Prompt.md", "gemini": "제미나이.png", "gpt": "GPT.jpg"},
  {"n": 5, "name": "수묵화", "desc": "조선시대 인물 전통 수묵화", "dir": "수묵화", "doc": "Korean_Ink_Wash_Portrait_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 4, "name": "동네 백수", "desc": "골목 슈퍼 앞 빈티지 트레이닝복", "dir": "동네 백수", "doc": "Neighborhood_Slacker_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 3, "name": "귀여운 케릭터", "desc": "작고 하얀 동물형 생물 캐릭터", "dir": "귀여운 케릭터", "doc": "Cute_Character_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 2, "name": "야쿠자", "desc": "여성 야쿠자 이아이도 발도술", "dir": "야쿠자", "doc": "Female_Yakuza_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"},
  {"n": 1, "name": "두정갑", "desc": "조선시대 무관 구군복", "dir": "두정갑", "doc": "Joseon_Military_Officer_Prompt.md", "gemini": "제미나이.jpg", "gpt": "GPT.jpg"}
];
